# -*- coding: utf-8 -*-
"""urb_def1_country_panel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/tannerregan/UTIC/blob/main/code/urb_def1_country_panel.ipynb
"""

#!pip install earthengine-api
!earthengine authenticate

!pip install pyreadstat
!pip install pycountry_convert

import os
import dask.dataframe as dd
import pandas as pd
import pycountry_convert as pc
import pyreadstat

mainpath="/content/drive"
from google.colab import drive
drive.mount(mainpath)

# Define the folder containing the CSV files
inpath=mainpath+"/MyDrive/UTIC/_data"
dir_path=inpath+'/gen/urb1'
save_to=inpath+'/gen'

import ee

ee.Initialize()


# -------------------------------------------
# 1) SETUP & DATA IMPORT
# -------------------------------------------
# Country boundaries
countries = ee.FeatureCollection('FAO/GAUL/2015/level0')

# Import SMOD & POP images
smod1980 = ee.Image('JRC/GHSL/P2023A/GHS_SMOD/1980').select('smod_code')
smod1990 = ee.Image('JRC/GHSL/P2023A/GHS_SMOD/1990').select('smod_code')
smod2000 = ee.Image('JRC/GHSL/P2023A/GHS_SMOD/2000').select('smod_code')
smod2010 = ee.Image('JRC/GHSL/P2023A/GHS_SMOD/2010').select('smod_code')
smod2020 = ee.Image('JRC/GHSL/P2023A/GHS_SMOD/2020').select('smod_code')

pop1980 = ee.Image('JRC/GHSL/P2023A/GHS_POP/1980')
pop1990 = ee.Image('JRC/GHSL/P2023A/GHS_POP/1990')
pop2000 = ee.Image('JRC/GHSL/P2023A/GHS_POP/2000')
pop2010 = ee.Image('JRC/GHSL/P2023A/GHS_POP/2010')
pop2020 = ee.Image('JRC/GHSL/P2023A/GHS_POP/2020')

# -------------------------------------------
# 2) HELPER FUNCTIONS
# -------------------------------------------

def createUrbanLayer1(image):
    return image.eq(22).Or(image.eq(23)).Or(image.eq(30)) \
               .multiply(1).rename('urban')
def createUrbanLayer2(image):
    return image.eq(21).Or(image.eq(22)).Or(image.eq(23)).Or(image.eq(30)) \
               .multiply(1).rename('urban')


def exportRasterByCountry(raster, rasterLabel, filePrefix):
    clean = raster.updateMask(raster.gte(0))
    band0raw = clean.select(0)
    targetScale = 1000
    projAt1k = band0raw.projection().atScale(targetScale)
    band0 = band0raw.setDefaultProjection(projAt1k)
    agg1km = band0.reduceResolution(
        reducer=ee.Reducer.sum().unweighted(),
        maxPixels=1024
    ).reproject(
        crs=projAt1k,
        scale=targetScale
    )
    aggName = agg1km.bandNames().get(0)

    def mapCountry(feat):
        geom = feat.geometry()
        stats = agg1km.reduceRegion(
            reducer=ee.Reducer.sum().unweighted(),
            geometry=geom,
            scale=targetScale,
            maxPixels=1e13,
            tileScale=8
        )
        sum_val = stats.get(aggName)
        return ee.Feature(None).set('country', feat.get('ADM0_NAME')).set(rasterLabel, sum_val)

    byCountry = countries.map(mapCountry)

    task = ee.batch.Export.table.toDrive(
        collection=byCountry,
        description=filePrefix,
        folder='urb2', # make shortcut for target folder in drive before running
        fileNamePrefix=filePrefix,
        fileFormat='CSV',
        selectors=['country', rasterLabel]
    )
    task.start()

# -------------------------------------------
# 3) DERIVED RASTERS & EXPORT PREP
# -------------------------------------------
landArea = ee.Image.pixelArea().rename('land_area') \
    .setDefaultProjection(smod2020.projection().atScale(1000))

#change function to switch between def 1 and def 2
urb1980 = createUrbanLayer2(smod1980)
urb1990 = createUrbanLayer2(smod1990)
urb2000 = createUrbanLayer2(smod2000)
urb2010 = createUrbanLayer2(smod2010)
urb2020 = createUrbanLayer2(smod2020)

urbMap = {1980: urb1980, 1990: urb1990, 2000: urb2000, 2010: urb2010, 2020: urb2020}
popMap = {1980: pop1980,  1990: pop1990,  2000: pop2000, 2010: pop2010, 2020: pop2020}
years = [1990, 2000, 2010, 2020]
exportsList = []

for t in years:
    lag = t - 10
    u_t = urbMap[t]
    u_lag = urbMap[lag]
    p_t = popMap[t]
    p_lag = popMap[lag]

    exportsList.append({'img': landArea, 'label': f'land_area_{t}', 'prefix': 'land_area'})
    exportsList.append({'img': p_t,        'label': f'population_{t}',  'prefix': 'population'})

    landShr = u_t.multiply(ee.Image.pixelArea()).divide(landArea).rename(f'land_shr_urb_{t}')
    exportsList.append({'img': landShr,     'label': f'land_shr_urb_{t}', 'prefix': 'land_shr_urb'})

    periMask = u_t.eq(1).And(u_lag.eq(0))
    landShrPeri = periMask.multiply(ee.Image.pixelArea()).divide(landArea).rename(f'land_shr_urb_peri_{t}')
    exportsList.append({'img': landShrPeri, 'label': f'land_shr_urb_peri_{t}', 'prefix': 'land_shr_urb_peri'})

    popUrb = u_t.multiply(p_t).rename(f'pop_urb_{t}')
    exportsList.append({'img': popUrb,      'label': f'pop_urb_{t}',      'prefix': 'pop_urb'})

    popChg = p_t.subtract(p_lag).multiply(u_t).rename(f'pop_chng_urb_{t}')
    exportsList.append({'img': popChg,      'label': f'pop_chng_urb_{t}', 'prefix': 'pop_chng_urb'})

    popPeriChg = p_t.subtract(p_lag).multiply(periMask).rename(f'pop_chng_urb_peri_{t}')
    exportsList.append({'img': popPeriChg,  'label': f'pop_chng_urb_peri_{t}', 'prefix': 'pop_chng_urb_peri'})


# -------------------------------------------
# 4) EXPORT TEST RUN
# -------------------------------------------
# Instead of exporting all rasters, run one test export:
# Using the first entry in exportsList (e.g. land_area_1990)
#test_item = exportsList[16]
#exportRasterByCountry(
 #   test_item['img'],
  #  test_item['label'],
   # test_item['label']
#)
# End test run

# -------------------------------------------
# 4) EXPORT LOOP
# -------------------------------------------
for item in exportsList:
    exportRasterByCountry(item['img'], item['label'], item['label'])

pop_def1 = dir_path  # urban class 1 data folder
results1 = save_to   # urban class 1 result folder

#
# --------------- urban definition 1 ------------------------------

# Loop through all files in the folder and create a list of DataFrames
dataframes = []
for i, filename in enumerate(os.listdir(pop_def1)):
    if filename.endswith(".csv"):
        file_path = os.path.join(pop_def1, filename)

        # Read the CSV using Dask
        df = dd.read_csv(file_path)

        # Round all population columns to whole numbers (if not the 'country' column)
        for col in df.columns:
            if col != "country":
                df[col] = df[col].round(0).astype("Int64")  # Round nd convert to integer

        # If not the first file, drop the 'country' column.
        if i != 0:
            df = df.drop(columns=["country"])

        dataframes.append(df)

# Concatenate all DataFrames
merged_df = dd.concat(dataframes, axis=1)

# Merge rows with the same country name and sum their values.
merged_df = merged_df.groupby("country").sum().reset_index()

# create population pandas datafram
data = merged_df.compute()

# create function to rename country with pycountry_convert recognized country name
def country_renamer(data_name, real_name):
    data_n = data.replace(data_name, real_name)
    return data_n

# rename country names to match names recognized by pycountry_convert for easy continent identification
data = country_renamer("U.K. of Great Britain and Northern Ireland", "Great Britain")
data = country_renamer("China/India", "China")
data = country_renamer("Iran  (Islamic Republic of)", "Iran, Islamic Republic of")
data = country_renamer("Micronesia (Federated States of)", "Micronesia, Federated States of")
data = country_renamer("Turks and Caicos islands", "Turks and Caicos Islands")
data = country_renamer("Timor-Leste", "Timor-Leste")
data = country_renamer("Republic of Korea", "Korea, Republic Of")
data = country_renamer("Saint Pierre et Miquelon", "Saint Pierre and Miquelon")
data = country_renamer("Svalbard and Jan Mayen Islands", "Svalbard and Jan Mayen")
data = country_renamer("Saint Helena", "Saint Helena, Ascension and Tristan da Cunha")
data = country_renamer("Dem People's Rep of Korea", "Democratic People's Republic of Korea")
data = country_renamer("The former Yugoslav Republic of Macedonia", "Macedonia, The Former Yugoslav Republic Of")


# define function to add continent name
def country_to_continent(country_name):
    try:
        country_alpha2 = pc.country_name_to_country_alpha2(country_name)
        country_continent_code = pc.country_alpha2_to_continent_code(country_alpha2)
        country_continent_name = pc.convert_continent_code_to_continent_name(country_continent_code)
        return country_continent_name
    except KeyError as e:
        return None

# insert continent column beside the country column
country_name = data["country"]  # list with country names
continent_name = [country_to_continent(i) for i in country_name] # list with continent names
data.insert(1, "continent", continent_name)  # insert column

# rename population data country names to match Income class country name for better merge
data = country_renamer("Bahamas", "Bahamas, The")
data = country_renamer("Cape Verde", "Cabo Verde")
data = country_renamer("Czech Republic", "Czechia")
data = country_renamer("Congo, Dem. Rep.", "Democratic Republic of the Congo")
data = country_renamer("Congo, Rep.", "Republic of the Congo")
data = country_renamer(r"CÃ´te d'Ivoire", "Cote d'Ivoire")
data = country_renamer("Moldova", "Moldova, Republic of")

# group by country name and sum
data = data.groupby("country").sum().reset_index()


####### Generate summary statistics by region ##############

# Import income data
incomeGroup = pd.read_csv(inpath + r"/income_class.csv")
incomeGroup = incomeGroup[["Economy", "Code", "Region", "Income group"]] # keep only relevant columns
incomeGroup = incomeGroup.rename(columns={"Economy": "country"})  # rename column to match main data column
popData = data.merge(incomeGroup, how="left", on="country") # merge income group with population data by country name


# Compute the final merged result and save it to a new CSV file -
popData.to_csv(results1 + r"/urb_data1.csv")
print(f'Main population data saved at: {results1}')

del popData["continent"]  # remove continent column as it is not needed for the panel format
del popData["Region"]
del popData["Income group"]


# Reshape the DataFrame to a panel format
# This will convert the DataFrame from wide format to long format and then back to wide format with 'var' as columns.


# Melt everything except 'country' into long form
melted = popData.melt(
    id_vars=["country", "Code"],
    var_name="variable",
    value_name="value"
)

# Split the variable names at the last underscore to get ‘var’ and ‘year’
melted[["var", "year"]] = (
    melted["variable"]
    .str.rsplit("_", n=1, expand=True)
)

#Pivot back out so each var becomes its own column
df_panel = (
    melted
    .pivot_table(
        index=["country", "Code", "year"],
        columns="var",
        values="value"
    )
    .reset_index()
)

# Flatten the columns
df_panel.columns.name = None

#print(df_panel.head())

df_panel = df_panel.rename(columns={"Code": "country_code"})  # rename column to match main data column
# Convert 'year' to integer type
df_panel["year"] = df_panel["year"].astype(int)
# Convert 'country_code' to string type
df_panel["country_code"] = df_panel["country_code"].astype(str)
# Convert 'country' to string type
df_panel["country"] = df_panel["country"].astype(str)
df_panel["land_area"] = df_panel["land_area"]/1000000 # divide land area by 1,000,000 to convert to square kilometers
df_panel.rename(columns={'land_shr_urb1': 'land_urb1'}, inplace="TRUE")
df_panel.rename(columns={'land_shr_urb1_peri': 'land_urb1_peri'}, inplace="TRUE")

# save to a new CSV file -
df_panel.to_csv(results1 + r"/urb_def1_country_panel.csv")

# Define variable labels
variable_labels = {
    'country': 'Country name',
    'country_code': 'Country code',
    'year': 'Year',
    'land_area': 'Country land area in km',
    'population': 'Country population in t',
    'land_urb1': 'Land that is urban1 at t in km',
    'land_urb1_peri': 'Urban1 land at t that was not urban1 in t-10',
    'pop_urb': 'Population that is urban1 at t',
    'pop_chng_urb1': 'Change in population from t-10 to t on land that is urban1 at t',
    'pop_chng_urb1_peri': 'Change in population from t-10 to t on land that is urban1 at t and NOT urban1 at t-10'
}

# Specify full path
output_path = save_to + r"/urb_def1_country_panel.dta"

# Save with labels
pyreadstat.write_dta(df_panel, output_path, column_labels=variable_labels)

print(f"Saved to {output_path}")
# Save to Stata with labels using pyreadstat
dta = pyreadstat.write_dta(df_panel, 'df_panel.dta', column_labels=variable_labels)





